// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Data;

#nullable disable

namespace SalesManagement.Migrations
{
    [DbContext(typeof(SalesManagementContext))]
    partial class SalesManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Passive Components"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Semiconductors"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Voltage Regulators"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Microcontrollers"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Sensors"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Modules"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Connectors"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Power Electronics"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Displays"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Memory Chips"
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ali",
                            LastName = "Khosravi"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Reza",
                            LastName = "Ghavami"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sina",
                            LastName = "Ahmadi"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Nima",
                            LastName = "Karimi"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Farhad",
                            LastName = "Nikbakht"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Ehsan",
                            LastName = "Rahmani"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Mina",
                            LastName = "Sadeghi"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Mahdi",
                            LastName = "Hashemi"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Parsa",
                            LastName = "Ghanbari"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Hassan",
                            LastName = "Moradi"
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MinQuantity = 10,
                            Price = 200m,
                            Title = "Resistor 10kΩ 1/4W",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MinQuantity = 10,
                            Price = 150m,
                            Title = "Resistor 1kΩ 1/4W",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MinQuantity = 20,
                            Price = 3000m,
                            Title = "Capacitor 100uF 25V",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MinQuantity = 20,
                            Price = 3500m,
                            Title = "Capacitor 470uF 16V",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MinQuantity = 10,
                            Price = 1200m,
                            Title = "Transistor 2N2222 NPN",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MinQuantity = 5,
                            Price = 9000m,
                            Title = "MOSFET IRFZ44N",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MinQuantity = 10,
                            Price = 4000m,
                            Title = "Voltage Regulator 7805",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            MinQuantity = 3,
                            Price = 58000m,
                            Title = "ATmega328P-PU",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            MinQuantity = 5,
                            Price = 25000m,
                            Title = "DS18B20 Temperature Sensor",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            MinQuantity = 2,
                            Price = 120000m,
                            Title = "OLED Display 0.96 I2C",
                            TypeId = 10
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Title = "1/4W Resistor"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Title = "Electrolytic Capacitor"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Title = "NPN Transistor"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Title = "MOSFET"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Title = "7805 Regulator"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Title = "ATmega Series"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Title = "Temperature Sensor"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Title = "Relay Module"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Title = "JST Connector"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            Title = "OLED Display"
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateTime = new DateTime(2025, 11, 22, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5769),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DateTime = new DateTime(2025, 11, 21, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5786),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DateTime = new DateTime(2025, 11, 20, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5790),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DateTime = new DateTime(2025, 11, 19, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5792),
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            DateTime = new DateTime(2025, 11, 18, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5794),
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            DateTime = new DateTime(2025, 11, 17, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5796),
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            DateTime = new DateTime(2025, 11, 16, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5797),
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            DateTime = new DateTime(2025, 11, 15, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5798),
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 9,
                            DateTime = new DateTime(2025, 11, 14, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5800),
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            DateTime = new DateTime(2025, 11, 13, 17, 56, 17, 730, DateTimeKind.Local).AddTicks(5801),
                            Type = 1
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.TransactionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionProduct");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 1000,
                            TransactionId = 1,
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 800,
                            TransactionId = 1,
                            UnitPrice = 150m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 200,
                            TransactionId = 2,
                            UnitPrice = 3000m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 150,
                            TransactionId = 2,
                            UnitPrice = 3500m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 100,
                            TransactionId = 3,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 50,
                            TransactionId = 3,
                            UnitPrice = 9000m
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 1,
                            Quantity = 100,
                            TransactionId = 4,
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 3,
                            Quantity = 20,
                            TransactionId = 5,
                            UnitPrice = 3000m
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 8,
                            Quantity = 20,
                            TransactionId = 6,
                            UnitPrice = 58000m
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 9,
                            Quantity = 40,
                            TransactionId = 6,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 9,
                            Quantity = 5,
                            TransactionId = 7,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 10,
                            Quantity = 10,
                            TransactionId = 8,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 10,
                            Quantity = 1,
                            TransactionId = 9,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 2,
                            Quantity = 50,
                            TransactionId = 10,
                            UnitPrice = 150m
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ehsan",
                            LastName = "Arefzadeh"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Reza",
                            LastName = "Naghavi"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sina",
                            LastName = "Moradi"
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Product", b =>
                {
                    b.HasOne("SalesManagement.Models.Entities.ProductType", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.ProductType", b =>
                {
                    b.HasOne("SalesManagement.Models.Entities.Category", "Category")
                        .WithMany("ProductTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Transaction", b =>
                {
                    b.HasOne("SalesManagement.Models.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.TransactionProduct", b =>
                {
                    b.HasOne("SalesManagement.Models.Entities.Product", "Product")
                        .WithMany("TransactionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Models.Entities.Transaction", "Transaction")
                        .WithMany("TransactionProducts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Category", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Product", b =>
                {
                    b.Navigation("TransactionProducts");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesManagement.Models.Entities.Transaction", b =>
                {
                    b.Navigation("TransactionProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
